server:
    verbosity: 0
    username: ""
    chroot: ""
    pidfile: ""
    use-syslog: no
    logfile: ""
    interface: 127.0.0.1
    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    access-control: 127.0.0.0/8 allow
    root-hints: "/etc/unbound/root.hints"
    hide-identity: yes
    hide-version: yes
    qname-minimisation: yes
    cache-min-ttl: 300
    cache-max-ttl: 86400
    prefetch: yes
    num-threads: 1
    private-address: 192.168.0.0/16
    private-address: 10.0.0.0/8
    private-address: 172.16.0.0/12
