#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev 2>/dev/null
if ! mount -t devtmpfs none /dev 2>/dev/null; then
    mknod /dev/console c 5 1
    mknod /dev/null c 1 3
    mknod /dev/tty c 5 0
    mknod /dev/ttyS0 c 4 64
    mknod /dev/tty0 c 4 0
fi
sleep 1
dmesg -n 1
for CON in /dev/tty0 /dev/ttyS0; do
    clear > $CON 2>/dev/null
    echo "================================" > $CON
    echo "     Welcome to Umbrella OS" > $CON
    echo "================================" > $CON
done
export PS1='UmbrellaOS # '
while true; do /bin/busybox setsid /bin/busybox cttyhack /bin/sh </dev/ttyS0 >/dev/ttyS0 2>&1; done &
while true; do /bin/busybox setsid /bin/busybox cttyhack /bin/sh </dev/tty0 >/dev/tty0 2>&1; done
