#!/bin/busybox sh

/bin/busybox mount -t proc none /proc
/bin/busybox mount -t sysfs none /sys
/bin/busybox mount -t devtmpfs none /dev

/bin/busybox --install -s /bin

dmesg -n 1

exec /bin/busybox init
