#!/bin/bash

build() {
    add_binary /home/user/umbrella_os/build/busybox-1.37.0/busybox /bin/busybox
    add_file /home/user/umbrella_os/scripts/init /init
    chmod 755 "${BUILDROOT}/init"
    add_file /home/user/umbrella_os/scripts/inittab /etc/inittab
    add_file /home/user/umbrella_os/scripts/rcS /etc/init.d/rcS
    chmod 755 "${BUILDROOT}/etc/init.d/rcS"
    add_file /home/user/umbrella_os/scripts/udhcpc.script /etc/udhcpc.script
    chmod 755 "${BUILDROOT}/etc/udhcpc.script"
    add_file /home/user/umbrella_os/scripts/profile /etc/profile
    add_file /home/user/umbrella_os/scripts/shell /etc/shell
    chmod 755 "${BUILDROOT}/etc/shell"
    add_file /home/user/umbrella_os/installer/install.sh /installer/install.sh
    chmod 755 "${BUILDROOT}/installer/install.sh"
    add_dir /boot
    add_file /home/user/umbrella_os/iso/boot/vmlinuz /boot/vmlinuz
    add_file /home/user/umbrella_os/iso/boot/initramfs.img /boot/initramfs.img
    add_binary /usr/bin/parted
    add_binary /usr/bin/mkfs.fat
    add_binary /usr/sbin/mkfs.ext4
    add_binary /usr/sbin/grub-install 
    add_binary /usr/bin/lsblk
    add_full_dir /usr/lib/grub/x86_64-efi
    add_full_dir /usr/share/grub
    add_dir /proc
    add_dir /sys
    add_dir /dev
    add_dir /bin
    add_dir /etc
    add_dir /etc/init.d
    add_dir /sbin
    add_dir /mnt
    add_dir /installer
    add_dir /usr
    add_dir /usr/lib
    add_dir /usr/lib/grub
    add_dir /usr/share
}

help() {
    echo "Umbrella OS base hook"
}
