#!/bin/sh

for iface in $(ls /sys/class/net/); do
    [ "$iface" = "lo" ] && continue
    ip link set "$iface" up
    udhcpc -i "$iface" -q -s /etc/udhcpc.script -t 3 -T 2 -n 2>/dev/null && break
done

export PS1='UmbrellaOS # '

clear
echo "================================"
echo "      Welcome to Umbrella OS    "
echo "================================"
