#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export HOME=/root
export PS1='UmbrellaOS # '
umask 027

clear
echo "================================"
echo "      Welcome to Umbrella OS    "
echo "================================"

exec /bin/sh
